### ISSUE TITLE
Worker Time outs

### ISSUE THREAD

**Issue by jvijay-work** [catmullet/go-workers#2]
**Is your feature request related to a problem? Please describe.**
What if I want to only wait, say, 100 seconds per worker

**Describe the solution you'd like**
After n seconds terminate worker and send err message

**Comment by catmullet** [comment]
Thank you for submitting the issue.  It was in fact an issue with it timing out when an error bubbles up.  We've fixed the workers timeout issue and added an example like the problem you presented.  Let us know if that doesn't work for you.  Thank you again! https://github.com/catmullet/go-workers/commit/b0fef67aaddb05ed6782493cc0f94636649ee77f
