### ISSUE TITLE
Error not bubbling up

### ISSUE THREAD

**Issue by nanikjava** [catmullet/go-workers#30]
**Describe the bug**
The error returned from the worker are not bubbling up

**To Reproduce**
```
package main

import (
	"context"
	"errors"
	"fmt"
	"github.com/catmullet/go-workers"
)

func main() {
	ctx := context.Background()
	rnr := workers.NewRunner(ctx, NewWorker(), 1).Start()

	rnr.Send("Print this out")

	if err := rnr.Wait(); err != nil {
		fmt.Println(err)
	}

}

type MyWorker struct {
}

func NewWorker() workers.Worker {
	return &MyWorker{}
}

func (wo *MyWorker) Work(in interface{}, out chan<- interface{}) error {
	return errors.New("empty name")
}
```
**Expected behavior**
From documentation the error code should be printed out but it's empty (nil)

**Comment by nanikjava** [comment]
Looks like the problem is inside the following piece of code inside `startWork()`.

```
if workErr := r.workFunc(in, r.outChan); workErr != nil {
		r.once.Do(func() {
			errors.As(err, &workErr)
			r.cancel()
			return
		})
	}
```

playing around with the code noticed that the when the `err` is `nil` (which is always) the error from the worker is not available. However, playing around the code and adding the following can see that the `.As` function works

```
	if workErr := r.workFunc(in, r.outChan); workErr != nil {
		r.once.Do(func() {
			err = context.Canceled
			errors.As(err, &workErr)
			r.cancel()
			return
		})
	}
```

**Comment by catmullet** [comment]
@nanikjava, Thank you for taking the time to submit an issue. There is definitely an issue where an error will not bubble up. The unit tests for testing a return of an error did not catch it.  I am currently working on a solution for this.

**Comment by nanikjava** [comment]
Tested the referenced PR https://github.com/catmullet/go-workers/pull/31 and it works.

Closing the ticket.
